---
- name: set the name of the bucket
  set_fact: s3_bucket="{{ ansible_date_time.epoch }}-openshift-docker-registry"
- name: Create S3 bucket
  s3:
    bucket: "{{ s3_bucket }}"
    mode: create
    region: "{{ region }}"
