---
- name: Gather facts
  openshift_facts:
    role: common

- name: Install the required rpms
  package: name="{{ item }}" state=latest
  with_items:
  - NetworkManager
  - iptables-services


- name: Start NetworkManager
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - NetworkManager
  - iptables-services

  when: not openshift.common.is_atomic | bool

- name: Install the required rpms
  package: name=* state=latest
  when: not openshift.common.is_atomic | bool
