---
- name: Add DNS entry to Route53
  route53:
     command: create
     zone: "{{ public_hosted_zone }}"
     record: "{{ app_instance_prefix }}01.{{ public_hosted_zone }}"
     type: A
     ttl: 60
     value: "{{ item.private_ip }}"
     overwrite: yes
  with_items: app0.instances
- name: Create Reverse DNS records
  route53:
    command: create
    zone: "{{ reverse_addr }}"
    overwrite: yes
    record: "{{ item.private_ip | ipaddr('revdns') }}"
    type: PTR
    value: "{{ app_instance_prefix }}01.{{ public_hosted_zone }}"
  with_items: app0.instances
- name: Add DNS entry to Route53
  route53:
     command: create
     zone: "{{ public_hosted_zone }}"
     record: "{{ app_instance_prefix }}02.{{ public_hosted_zone }}"
     type: A
     ttl: 60
     value: "{{ item.private_ip }}"
     overwrite: yes
  with_items: app1.instances
- name: Create Reverse DNS records
  route53:
    command: create
    zone: "{{ reverse_addr }}"
    overwrite: yes
    record: "{{ item.private_ip | ipaddr('revdns') }}"
    type: PTR
    value: "{{ app_instance_prefix }}02.{{ public_hosted_zone }}"
  with_items: app1.instances
