---
- name: create instance groups
  hosts: localhost
  roles:
  - instance-groups

- include: ../../../../playbooks/prerequisite.yaml
- include: ../../../../playbooks/openshift-storage.yaml
- include: openshift-setup.yaml
- include: ../../../../playbooks/empty-dir-quota.yaml

- name: post ocp deploy tasks for master nodes
  hosts: masters
  roles:
  - master-http-proxy
  - role: os_firewall
    os_firewall_allow:
    - service: master http proxy
      port: 8080/tcp

- name: post ocp deploy tasks for infra nodes
  hosts: infra_nodes
  roles:
  - role: os_firewall
    os_firewall_allow:
    - service: router liveness probe
      port: 1936/tcp

- name: post ocp deploy tasks for app nodes
  hosts: app_nodes
  roles:
  - restrict-gce-metadata

- name: deploy registry
  hosts: single_master
  roles:
  - openshift-registry

- include: validation.yaml

- name: print message about the ocp console
  hosts: localhost
  roles:
  - final-message
