- hosts: localhost
  connection: local
  gather_facts: yes 
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      # Group systems
      - cfn-outputs
      - instance-groups

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      - host-up

- hosts: cluster_hosts
  gather_facts: yes 
  become: yes
  serial: 1
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - rhsm-subscription

- hosts: cluster_hosts
  gather_facts: no
  become: yes
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - rhsm-repos
      - prerequisite 

- include: openshift-setup.yaml
