- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      # Group systems
      - instance-groups

- hosts: localhost
  gather_facts: no
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      - validate-public

- hosts: masters
  gather_facts: no
  vars_files:
      - vars/main.yaml
  roles:
      - validate-masters

- hosts: masters
  gather_facts: yes
  vars_files:
      - vars/main.yaml
  roles:
      - validate-etcd

- hosts: primary_master
  gather_facts: yes 
  become: yes
  vars_files:
      - vars/main.yaml
  roles:
      - validate-app
