---
- name: Gather facts
  openshift_facts:
    role: common

- name: Set Origin fact
  set_fact:
    openshift_release: 1.5.0
  when: deployment_type == "origin"

- block:
  - name: Clear yum cache
    command: "yum clean all"
    ignore_errors: true

  - name: Install the required rpms
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - iptables
    - iptables-services
    - NetworkManager

  - name: Start NetworkManager and network
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    with_items:
    - NetworkManager
    - network

  - name: Determine if firewalld is installed
    rpm_q:
      name: "firewalld"
      state: present
    register: firewalld_installed
    failed_when: false

  - name: Stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
    when:
    - "{{ firewalld_installed.installed_versions | default([]) | length > 0 }}"

  - name: Start iptables
    service:
      name: iptables
      state: started
      enabled: true

  when: not openshift.common.is_atomic | bool
