---
templatelink: "https://raw.githubusercontent.com/openshift/openshift-ansible-contrib/master/reference-architecture/azure-ansible/azuredeploy.json"
numberofnodes: 3
image: "rhel"
mastervmsize: "Standard_DS3_v2"
infranodesize: "Standard_DS3_v2"
nodevmsize: "Standard_DS12_v2"
location: "westus"
metrics: true
