---
- name: Create haproxy VM on vCenter
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ item.value.guestname }}"
    cluster: "{{ vcenter_cluster}}"
    resource_pool: "{{ vcenter_resource_pool }}"
    from_template: yes
    template_src: "{{vcenter_template_name}}"
    vm_extra_config:
      notes: "{{ item.value.tag }}"
      folder: "{{ vcenter_folder }}"
  with_dict: "{{infrastructure_hosts}}"
  when: item.value.guestname == 'haproxy-0'

- name: Get facts of haproxy VM
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    vmware_guest_facts: yes
    guest: "{{ infrastructure_hosts.haproxy.guestname }}"
  register: actual_haproxy_host
  until: actual_haproxy_host.ansible_facts.hw_eth0.ipaddresses[0] is defined
  retries: 10
  delay: 10

- name: Add haproxy server to inventory
  add_host: hostname={{actual_haproxy_host.ansible_facts.hw_name}} ansible_ssh_host={{actual_haproxy_host.ansible_facts.hw_eth0.ipaddresses[0]}} groups="haproxy_group"
