---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - create-vm-cns-prod-ose
  - instance-groups

- hosts: storages
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - rhel_subscribe
  - vmware-guest-setup
  - gluster-ports
- include: ../../../playbooks/openshift-storage.yaml
#- include: ../../../playbooks/add-node-prerequisite.yaml

- include: node-setup.yaml
