---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - create-vm-crs-prod-ose
  - instance-groups
  tags: [ 'vms' ]

- hosts: crs
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  # rhel_subscribe attempts to use ose repos
  - instance-groups
  - rhsm-subscription
  - gluster-rhsm-repos
  - vmware-guest-setup
  - gluster-crs-prerequisites
  - gluster-ports
  tags: [ 'crs-node-setup' ]

- hosts: localhost
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  - rhsm-subscription
  - gluster-rhsm-repos
  - heketi-install
  - heketi-configure
  tags: [ 'heketi-setup' ]

- hosts: master
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  tags: [ 'heketi-ocp' ]

- hosts: single_master
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  - heketi-ocp
  tags: [ 'heketi-ocp' ]
