---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - create-vm-add-prod-ose

- hosts: new_nodes
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  - rhsm-subscription
  - rhsm-repos
  - vmware-guest-setup
- include: ../../../playbooks/openshift-storage.yaml
- include: ../../../playbooks/add-node-prerequisite.yaml

- include: node-setup.yaml

- hosts: loadbalancer, master, infra
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - haproxy-server-config

- hosts: single_master
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - ../../../roles/router-scaleup
