---
- hosts: crs
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  - rhsm
  - gluster-rhsm-repos
  - vmware-guest-setup
  - gluster-crs-prerequisites
  - gluster-ports
