- hosts: localhost
  gather_facts: yes
  vars_files:
      - ../vars/main.yaml
#      - ../vars/infrastructure.yaml

  roles:
      # Group systems
      - instance-groups

- hosts: localhost
  gather_facts: no
  vars_files:
      - ../vars/main.yaml
 #     - ../vars/infrastructure.yaml
  roles:
      - validate-public

- hosts: masters
  gather_facts: no
  vars_files:
      - ../vars/main.yaml
  #    - ../vars/infrastructure.yaml
  roles:
      - validate-masters

- hosts: masters
  gather_facts: yes
  vars_files:
      - ../vars/main.yaml
   #   - ../vars/infrastructure.yaml
  roles:
      - validate-etcd

- hosts: primary_master
  gather_facts: no
  vars_files:
      - ../vars/main.yaml
   #   - ../vars/infrastructure.yaml
  roles:
      - validate-app
