---
- hosts: localhost
  vars_files:
    - vars/main.yaml
  roles:
    - create-vm-prod-ose

- name: fulfill OSE3 prerequisites on production hosts roles
  hosts: production_group
  vars_files:
    - vars/main.yaml
  roles:
    - rhsm-subscription
    - rhsm-repos
    - vmware-guest-setup
