---
- name: Add bastion to group
  add_host:
    name: "bastion.{{ public_hosted_zone }}"
    groups: bastion
  when:
    - byo_bastion == "no"

- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: masters, etcd, nodes, cluster_hosts
    openshift_node_labels:
      role: master
  with_items: "{{ groups['tag_openshift_role_master'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}"

- name: Add a master to the primary masters group
  add_host:
    name: "{{ item }}"
    groups: primary_master
    openshift_node_labels:
      role: master
  with_items: "{{ groups['masters'].0 }}"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: infra
  with_items: "{{ groups['tag_openshift_role_infra'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: app
  with_items: "{{ groups['tag_openshift_role_app'] }}"
  when:
    - hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}"

- name: Add new node instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}" 
    groups: new_nodes
    openshift_node_labels:
      role: "{{ node_type }}" 
  with_items: "{{ groups.tag_provision_node | default([]) }}"
  when:
    - add_node is defined
    - hostvars[item]['ec2_tag_aws_cloudformation_stack_name'] == "{{ stack_name }}-{{ shortname }}"
