---
- name: Add masters to requisite groups
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: masters, etcd, nodes, cluster_hosts
    openshift_node_labels:
      role: master
  with_items: "groups['{{ master_group_tag }}']"

- name: Add a master to the primary masters group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: primary_master
    openshift_node_labels:
      role: master
  with_items: "groups['{{ master_group_tag }}'].0"

- name: Add infra instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: infra
  with_items: "groups['{{ infra_group_tag }}']"

- name: Add app instances to host group
  add_host:
    name: "{{ hostvars[item].ec2_tag_Name }}"
    groups: nodes, cluster_hosts, schedulable_nodes
    openshift_node_labels:
      role: app
  with_items: "groups['{{ app_group_tag }}']"
