---
- hosts: localhost
  tasks:
    - name: Check for required variables
      fail: 
         msg: "Please pass a valid provider: vsphere,aws,gcp,rhv e.g. -e provider=vsphere"
      when: provider is not defined

- hosts: localhost
  gather_facts: yes
  become: yes
  roles:
  - rhsm
  - deploy-host
