---
- name: Check for sat config file
  stat: path=/etc/rhsm/rhsm.conf.kat-backup
  register: sat_cfg

- name: Remove satellite configuration if using RH CDN
  command: "mv -f /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf"
  when: rhsm_user is defined and rhsm_user and sat_cfg.stat.exists == True
  ignore_errors: yes
 
- name: Remove satellite SSL if using RH CDN
  command: "rpm -e $(rpm -qa katello-ca-consumer*)"
  when: rhsm_user is defined and rhsm_user and sat_cfg.stat.exists == True
  ignore_errors: yes

- name: Is the host already registered?
  command: "subscription-manager list"
  register: subscribed
  ignore_errors: yes

- name: Register host via Activation key
  redhat_subscription:
    activationkey: "{{ rhsm_activation_key }}"
    org_id: "{{ rhsm_org_id }}"
    state: present
    pool: "{{ rhsm_pool }}"
  when: "'Subscribed' not in subscribed.stdout and rhsm_activation_key is defined and rhsm_activation_key"
  register: register_key_result
  ignore_errors: yes

- name: Register host via RH CDN
  redhat_subscription:
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    state: present
    pool: "{{ rhsm_pool }}"
  when: "'Subscribed' not in subscribed.stdout and rhsm_user is defined and rhsm_user"
  register: register_user_result
  ignore_errors: yes
